### ISSUE TITLE
Criação do Repositório

### ISSUE THREAD

**Issue by hvenanc** [hvenanc/GCMS-Henrique-Ven-ncio#1]
[README](https://github.com/hvenanc/GCMS-Henrique-Ven-ncio/blob/main/README.md)

**Comment by ramidedantas** [comment]
@hvenanc corrija o link para o README, acho que há um espaço entre o ] e o (.

**Comment by hvenanc** [comment]
@ramidedantas Corrigido!

**Comment by ramidedantas** [comment]
@hvenanc coloque no formato que está no meu repositório.

**Comment by hvenanc** [comment]
@ramidedantas Corrigido!

**Comment by ramidedantas** [comment]
@hvenanc OK, nome adicionado. Pode fechar a issue.
